project:
  type: website

website:
  title: "Triticum Tale"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: heat-stress.qmd
        text: Estrés Térmico
      - href: drought-stress.qmd
        text: Estrés Hídrico

format:
  html:
    theme: cosmo
    css: ../assets/custom_theme.css
    toc: true
